### ISSUE TITLE
Can sraplus support stock-specific effort and priors?

### ISSUE THREAD

**Issue by arni-magnusson** [DanOvando/sraplus#35]
https://github.com/sofia-tsaf/2021Area37Coastal/issues/2

**Comment by DanOvando** [comment]
I think I understand and broadly yes, though as you say in your message the key here is that`format_driors` itself is stock specific, so you'd need to do some looping / applying / mapping over individual stocks. I'll take a look at the example and might write up a vignette with the idea since it comes up a lot

**Comment by DanOvando** [comment]
@arni-magnusson can you point me towards the TAF package? I see this organization but don't seem to see a dedicated TAF package which I need to run data.R

**Comment by arni-magnusson** [comment]
@DanOvando thanks for the clarificiation!

The TAF package is on CRAN, but we can look at that stuff at an opportune time :)
